### PR TITLE
Remove tabindex hostAttribute, making iron-collapse non-focusable

### PR DESCRIPTION
**Pull request by punzki**
Fixes https://github.com/PolymerElements/iron-collapse/issues/10

### CODE REVIEW

**Comment by punzki** [comment]
The failed tests are not related to my changes.

**Comment by notwaldorf** [comment]
Could you sign the CLA so that we can merge this, please? :)

**Comment by punzki** [comment]
I signed it!

**Comment by punzki** [comment]
@notwaldorf - Not sure why googlebot is complaining about, since I'm the only committer in this pull request.

**Comment by punzki** [comment]
I signed it!

**Comment by notwaldorf** [comment]
Googlebot is a little bonkers at times :)

**Pull request merged**
